services:
  backend:
    build: .
    container_name: backend
    image: kovtaliv-backend
    restart: always
    command: >
      sh -c "
            python manage.py makemigrations missions &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
